### ISSUE TITLE
HTTPS access for OpenLayers.js?

### ISSUE THREAD

**Issue by dandv** [openlayers/ol2#1025]
I'm trying to use the latest API by linking directly to http://www.openlayers.org/api/OpenLayers.js. The problem is that when we've switched on HSTS, the .js wouldn't load:

```
[blocked] The page at https://blueseed.co/faq/#ship ran insecure content from http://www.openlayers.org/api/OpenLayers.js.
```

I've copied the .js to my server, but it would be nice if http<b>s</b>://www.openlayers.org/api/OpenLayers.js would be supported, so we can use protocol-less URIs as in c0bff1c.

(If there's another recommended way to do HTTPS, please let me know; a Google search wasn't very helpful.)

**Comment by fmalina** [comment]
HTTPS CDN URL for reference: https://cdnjs.cloudflare.com/ajax/libs/openlayers/2.13.1/OpenLayers.js
Full asset listings:
v2 https://cdnjs.com/libraries/openlayers
v3 https://cdnjs.com/libraries/ol3
