### ISSUE TITLE
Update NuGet package (and include it in new releases)

### ISSUE THREAD

**Issue by bsimser** [openlayers/ol2#1255]
The NuGet package for OpenLayers is from 2011 and running version 2.10.0 (http://www.nuget.org/packages/OpenLayers/). Please incorporate the NuGet build into new releases so the NuGet package is in sync, otherwise the NuGet package is pretty useless and we have to download and install things manually.

**Comment by Stockholmsnovis** [comment]
Hello. @bartvde May I ask why you choose not to create an official NuGet package?

**Comment by bartvde** [comment]
unfortunately no one has had the time
