### ISSUE TITLE
Please release an updated OpenLayers version 2

### ISSUE THREAD

**Issue by paladox** [openlayers/ol2#1490]
Theres been 500+ commits since the last release could this please be updated.

Also could there be some instructions on migrating to Version 3.

**Comment by bartvde** [comment]
releases are not free, they take time and money. Do you have funds available?

**Comment by paladox** [comment]
Oh I didn't know they cost money to release them, sorry.

**Comment by ahocevar** [comment]
@paladox There is a QA process involved in releasing OpenLayers 2. The procedure is quite demanding: https://trac.osgeo.org/openlayers/wiki/Release/Procedure. Back then when the project was set up, it was not so usual to have automated build processes like we do now for OpenLayers 3.

**Comment by TDesjardins** [comment]
Oh, oh, two requirements in one ticket ;-)

How much is a release? I was wondering about your anwers because until now the releases are "free", aren't they? I know there is ol3 and developing and maintaining a project costs time/money but there are also a lot of people who are making contributions for free waiting for a release and not knowing about the new policy. So it would be nice to have an information about it. I could add it to readme.md and create a pull request. Costs 20$ ;-)

**Comment by ahocevar** [comment]
@TDesjardins It's open source software - anyone can take the current code from master just like any release. Nobody is kept away from all the great contributions made since the last release.

**Comment by TDesjardins** [comment]
@ahocevar That's right. But that doesn't fits the missing information about the fact that there will be no free official ol2 release in the future. Thanks for your answer.

**Comment by marcjansen** [comment]
@TDesjardins no one said that. It's just effort involved in releasing, and I think that most developers of the openlayers team have shifted their interest over to v3.

**Comment by TDesjardins** [comment]
@marcjansen Nobody said that, but nobody will most likely deny it. Let's face it. The more changes made, the more effort is required for a release. Why a release should be made in future, when it is today already to costly?
That's ok! But in my opinion this is something the community or rather the users should know about.

And yes there is v3 and it is very impressive to watch its effective and fast development process. Thanks for that.

**Comment by probins** [comment]
It might be useful to add a note to http://openlayers.org/two/ stating that development is now concentrated on v3 and that support for v2 is limited and there probably won't be any more releases (if that's what the status is).

**Comment by ahocevar** [comment]
I agree @probins - actually I already started doing that, but couldn't come up with appropriate wording. Would you be able to help out and create that pull request? Thanks!

**Comment by probins** [comment]
ok, I'll add it to the list. :-)

**Comment by ahocevar** [comment]
Fixed with openlayers/openlayers.github.io#65.
