### ISSUE TITLE
Open source License obligations of openlayers-2.13.1

### ISSUE THREAD

**Issue by krushith720** [openlayers/ol2#1538]
Hello 

I wanted to build an application using ol2-release-2.13.1. When I looked in to the license, i have found that it is licensed under BSD-2 clause which was mentioned in license.txt file (ol2-release-2.13.1\license.txt). In addition, i have found an another folder called License (ol2-release-2.13.1\licenses) which includes copy of license text of Apache 2.0, BSD and MIT license. Could anybody please let me know, why are those license text is included?. Is the ol2-release-2.13.1 triple licensed? or whether license text applies to any of third party code included in it? If so, please let me know the dependencies.

Thank you.

Best, Kiran

**Comment by ahocevar** [comment]
The latter. The dependencies are Rico (Apache 2), and the Python minimizer (`tools/minimize.py`, MIT). The latter is a dev dependency.

**Comment by ahocevar** [comment]
That said, just in case you're considering OpenLayers 2 for a new project: don't. It's no longer maintained. OpenLayers 6 is the way to go - https://github.com/openlayers/openlayers.

**Comment by krushith720** [comment]
Hello @ahocevar 

Thanks for the information. If you include "Applicable to oss(for example-Rico)" above the license text, then it is easy to identify for which oss component the specific license is applicable to. 

Best,
Kiran
