### ISSUE TITLE
Google Map Layers not rendering anymore

### ISSUE THREAD

**Issue by ryan-mcalister** [openlayers/ol2#1542]
It seems a change in Google Maps makes OpenLayers freeze and not work anymore. If the google maps layer is removed then everything else works fine. There are no console warnings or errors.

**Comment by marcobrt** [comment]
Works for me, though I made a bunch of updates to Layer/Google/v3.js over the years.

**Comment by ryan-mcalister** [comment]
The issue seems fixed in the main branch of the project.
