### ISSUE TITLE
OpenLayers.Map.getSize returns (sometimes) null when map.div width or height is percentage while adding vector-Layers

### ISSUE THREAD

**Issue by fastrde** [openlayers/ol2#669]
the error looks like a timing issue. 
I try to explain it on a simple example...

``` javascript
<html>
<head>
<style>
  div#map{ width 100%; height: 100%; } //div#map width and height are percentage
</style>
</head>
<body>
<div id="map"></div>
<script>

  var map = new OpenLayers.map("map");
  var v1    = new OpenLayers.Layer.Vector("v1");
  var v2    = new OpenLayers.Layer.Vector("v2");
  var v3    = new OpenLayers.Layer.Vector("v3");

  var dump = clone(map); //function to clone(!) an object
  console.log(dump); //cloned map doesn't have a size object
  console.log(map); //TRAP: map has a size object in chrome devtools because the devtools shows the last state of the object.
  map.addLayers([v1,v2,v3]); //here getSize is called internally and the error occured sometimes
  map.setCenter(greatLocationToCenter);
</script>
</body>
</html>


```

I cloned the map Object before map.addLayers is called and it doesn't have a map.size object when the error happens.
Looks like the Browser (Chrome in my case) is not ready with calculating the pixel height and width at this moment. When you give static pixel values in css the error doesn't happen.
I can't reproduce the error with firefox on the same machine.  Maybe firefox ist faster in calculating the height/width or the internal handling is different.

Here are the Points where the error occured

Uncaught TypeError: Cannot read property 'w' of null in OpenLayers/Layer/Vector.js:400

``` javascript
 391     setMap: function(map) {
 392         OpenLayers.Layer.prototype.setMap.apply(this, arguments);
 393 
 394         if (!this.renderer) {
 395             this.map.removeLayer(this);
 396         } else {
 397             this.renderer.map = this.map;
 398 
 399             var newSize = this.map.getSize(); // here getSize returns null because map.size is not initialized
 400             newSize.w = newSize.w * this.ratio; //here happens the TypeError
 401             newSize.h = newSize.h * this.ratio;
 402             this.renderer.setSize(newSize);
 403         }
 404     },
```

Uncaught TypeError: Cannot read property 'w' of null im OpenLayers/Map.js:1787

``` javascript
1785     adjustZoom: function(zoom) {
1786         var resolution, resolutions = this.baseLayer.resolutions,
1787             maxResolution = this.getMaxExtent().getWidth() / this.size.w; //here this.size is null
1788         if (this.getResolutionForZoom(zoom) > maxResolution) {
1789             for (var i=zoom|0, ii=resolutions.length; i<ii; ++i) {
1790                 if (resolutions[i] <= maxResolution) {
1791                     zoom = i;
1792                     break;
1793                 }
1794             }
1795         }
1796         return zoom;
1797     },
```

**Comment by sis-yoshiday** [comment]
this issue 'sometimes' reproduce at Chromium (android 4.4 WebView).

but fastrde's workaround https://github.com/openlayers/openlayers/issues/669#issuecomment-8362375  worked.

**Comment by DudePascalou** [comment]
After some random searching in the js code, I found that I had to set size on another div that was titled "**olmap**" :
```html
<div id="olmap" style="height: 505px; width: 980px"></div>
```

**Comment by arjun810** [comment]
Some of our users are sporadically encountering this bug, but I haven't been able to personally reproduce it. Does anyone know how to reproduce it reliably so I can ensure I've fixed it? Thanks!

**Comment by fastrde** [comment]
if i remember correctly the bug is a race condition between the calculation of the sizes in the browser and the execution of a statement depending on that calculation. When you aren't able to prevent the browser to do the calculation you can't test it 100% reliable.

**Comment by quade1664** [comment]
Yes its a timing thing
Try putting a small wait ... that should fix it (not ideal!)



Thanks
Mark

**Comment by printmypic** [comment]
I have the same bug here version 3.7
strange when I open my app in incognito this problem is gone, maybe it related to cache stuff?

**Comment by bartvde** [comment]
This is not the bug tracker for version 3.x

**Comment by hutch120** [comment]
I've just encountered this issue on OpenLayers V2.13.1, and adapted the workaround documented here:
 http://thinkgeo.com/forums/MapSuite/tabid/143/aft/11896/Default.aspx

```
 this.OnMapCreating = function (map) {
	OpenLayers.Tile.prototype.destroy = function () {
		if (this.layer.map.tileManager != null) {
			OpenLayers.Util.removeItem(this.layer.map.tileManager.tileQueue[this.layer.map.id], this);
		}

		this.layer = null;
		this.bounds = null;
		this.size = null;
		this.position = null;

		if (this.eventListeners) {
			this.events.un(this.eventListeners);
		}
		this.events.destroy();
		this.eventListeners = null;
		this.events = null;
	};
}

that.OnMapCreating(OpenLayers.Map);
```
