### ISSUE TITLE
Zoomify - Wrong dimensions for marginal tiles for resolutions with dimensions dividable by tile size

### ISSUE THREAD

**Issue by michalbecak** [openlayers/ol2#928]
In Zoomify.js, in function getImageSize, there is block of code that counts width and height of image:
if (x == this.tierSizeInTiles[z].w -1 ){
  var w = this.tierImageSize[z].w % this.standardTileSize;
}
if (y == this.tierSizeInTiles[z].h -1 ) {
  var h = this.tierImageSize[z].h % this.standardTileSize;
}

However, for dimensions of tiers dividable by tile size (e.g. width of tier 768 and tile width 256) variable w will be 768 % 256 = 0.
I propose this change:
if (x == this.tierSizeInTiles[z].w -1 ) {
  var w = this.tierImageSize[z].w % this.standardTileSize;
  if (w == 0) w = this.standardTileSize;
}
if (y == this.tierSizeInTiles[z].h -1 ) {
  var h = this.tierImageSize[z].h % this.standardTileSize;
  if (h == 0) w = this.standardTileSize;
}
if (x == this.tierSizeInTiles[z].w) {
  w = Math.ceil(this.size.w / Math.pow(2, this.numberOfTiers - 1 - z) - this.tierImageSize[z].w);
}
if (y == this.tierSizeInTiles[z].h) {
  h = Math.ceil(this.size.h / Math.pow(2, this.numberOfTiers - 1 - z) - this.tierImageSize[z].h);
}

Last two conditions are because of JPEG 2000: in jp2 format, dimensions of tiles are ceiled (Math.ceil(Previous_dimension/2)), that means there may be requested part of image (1px usually) above dimension stated in tierImageSize. Without last two conditions, it would be resized to standardTileSize (for example 256px).

**Comment by moschlar** [comment]
Will there be a release that includes this fix?
